# Generated by Django 5.1.1 on 2024-09-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

operations = [
    migrations.AddField(
        model_name='producto',
        name='orden',
        field=models.PositiveIntegerField(default=0),
    ),
    migrations.AlterField(
        model_name='producto',
        name='Cantidad',
        field=models.IntegerField(),
    ),
    migrations.AlterField(
        model_name='producto',
        name='Precio',
        field=models.DecimalField(decimal_places=2, max_digits=10),
    ),
]
